services:
  langflow:
    image: langflowai/langflow:1.2.0
    restart: unless-stopped
    container_name: portainer-LangFlow
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    volumes:
      - portainer-langflow-data:/app/langflow
      - portainer-langflow-components:/app/custom_components/
    env_file:
      - ../../stack.env
      - stack.env

  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    container_name: portainer-PostgreSQL
    volumes:
      - portainer-postgres-data:/var/lib/postgresql/data
    env_file:
      - ../../stack.env
      - stack.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--host=localhost", "--username psql"]
      interval: 3s
      timeout: 3s
      retries: 10

  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    restart: unless-stopped
    container_name: portainer-LibreChat
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3080:3080"
    env_file:
      - ../../stack.env
      - stack.env
    volumes:
      - portainer-librechat-images:/app/client/public/images
      - portainer-librechat-logs:/app/api/logs
      - portainer-librechat-config:/app/config/
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: portainer-MongoDB
    volumes:
      - portainer-mongodb-data:/data/db
    command: mongod --noauth

  litellm:
    image: ghcr.io/berriai/litellm:litellm_stable_release_branch-v1.61.20-stable
    restart: unless-stopped
    container_name: portainer-litellm
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${LITELLM_DATABASE_URL}
    env_file:
      - ../../stack.env
      - stack.env
    depends_on:
      - postgres
    volumes:
      - portainer-litellm:/app/config
    command: "--config /app/config/litellm.yaml"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  langfuse-worker:
    image: langfuse/langfuse-worker:3
    restart: unless-stopped
    container_name: portainer-langfuse-worker
    depends_on: &langfuse-depends-on
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL=${LANGFUSE_DATABASE_URL}
    env_file:
      - ../../stack.env
      - stack.env

  langfuse-web:
    image: langfuse/langfuse:3
    container_name: portainer-langfuse-web
    restart: unless-stopped
    depends_on: *langfuse-depends-on
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${LANGFUSE_DATABASE_URL}
    env_file:
      - ../../stack.env
      - stack.env

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: portainer-clickhouse
    restart: unless-stopped
    user: "101:101"
    env_file:
      - ../../stack.env
      - stack.env
    volumes:
      - portainer-langfuse-clickhouse-data:/var/lib/clickhouse
      - portainer-langfuse-clickhouse-logs:/var/log/clickhouse-server
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s

  minio:
    image: minio/minio
    restart: unless-stopped
    container_name: portainer-minio
    entrypoint: sh
    # create the 'langfuse' bucket before starting the service
    command: -c 'mkdir -p /data/langfuse && minio server --address ":9000" --console-address ":9001" /data'
    env_file:
      - ../../stack.env
      - stack.env
    volumes:
      - portainer-langfuse-minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: portainer-redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
    env_file:
      - ../../stack.env
      - stack.env

  prometheus:
    image: prom/prometheus:v3.2.1
    restart: unless-stopped
    container_name: portainer-prometheus
    volumes:
      - portainer-prometheus-config:/etc/prometheus/config/
    command:
      - '--config.file=/etc/prometheus/config/prometheus.yml'

  librechat-metrics:
    image: ghcr.io/virtuos/librechat_exporter:main
    container_name: portainer-librechat-metrics
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - ../../stack.env
      - stack.env

  grafana:
    image: grafana/grafana-enterprise
    container_name: portainer-grafana
    restart: unless-stopped
    ports:
      - "3007:3000"
    volumes:
      - portainer-grafana-data:/var/lib/grafana

  helper-backend:
    image: hicsail/preaa-helper:main
    pull_policy: always
    container_name: portainer-helper-backend
    restart: unless-stopped
    ports:
      - "3008:3001"
    env_file:
      - ../../stack.env
      - stack.env

  chat-client:
    image: hicsail/preaa-chat-client:main
    pull_policy: always
    container_name: portainer-chat-client
    restart: unless-stopped
    ports:
      - "3009:80"
    env_file:
      - ../../stack.env
      - stack.env

  admin-client:
    image: hicsail/preaa-admin-client:main
    pull_policy: always
    container_name: portainer-admin-client
    restart: unless-stopped
    ports:
      - "3010:80"

  embedded-chat:
    image: hicsail/preaa-embedded-chat:main
    pull_policy: always
    container_name: portainer-admin-client
    restart: unless-stopped
    ports:
      - "3011:80"

volumes:
  portainer-langflow-data:
  portainer-langflow-components:
  portainer-postgres-data:
  portainer-librechat-images:
  portainer-librechat-logs:
  portainer-librechat-config:
  portainer-mongodb-data:
  portainer-litellm:
  portainer-langfuse-clickhouse-data:
  portainer-langfuse-clickhouse-logs:
  portainer-langfuse-minio-data:
  portainer-prometheus-config:
  portainer-grafana-data:
