scrape_configs:
  - job_name: 'librechat_metrics'
    scrape_interval: 60s
    static_configs:
      - targets:
          - 'librechat-metrics:8000'
  - job_name: 'langflow_metrics'
    scrape_interval: 60s
    static_configs:
      - targets:
          - 'langflow:9090'
