name: embedded-chat

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/embedded-chat/**'
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - 'packages/embedded-chat/**'
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check for Linting Errors
    defaults:
      run:
        working-directory: packages/embedded-chat
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: NPM Install
        run: npm install --only=dev
        shell: bash

      - name: Check for Linting Issues
        run: npm run prettier

  build:
    runs-on: ubuntu-latest
    name: Build Code
    defaults:
      run:
        working-directory: packages/embedded-chat
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: NPM Install
        run: npm install
        shell: bash

      - name: Build
        run: npm run build

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/embedded-chat
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Build (dev)
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ./packages/embedded-chat
          file: ./packages/embedded-chat/Dockerfile
          tags: hicsail/preaa-embedded-chat:main
          cache-from: type=gha,scope=gateway
          cache-to: type=gha,mode=max,scope=gateway
          build-args: |
              VITE_BACKEND_BASE_URL=${{ secrets.HELPER_BACKEND_URL }}

      - name: Build & Push Docker Build (prod)
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ./packages/embedded-chat
          file: ./packages/embedded-chat/Dockerfile
          tags: hicsail/preaa-embedded-chat:prod
          cache-from: type=gha,scope=gateway
          cache-to: type=gha,mode=max,scope=gateway
          build-args: |
              VITE_BACKEND_BASE_URL=${{ secrets.HELPER_BACKEND_URL_PROD }}


  deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: [docker]
    steps:
      - name: Push to Staging
        uses: fjogeleit/http-request-action@v1
        with:
          method: "POST"
          url: ${{ secrets.PORTAINER_WEBHOOK }}
          preventFailureOnNoResponse: true
