name: langflow

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/langflow/**'
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - 'packages/langflow/**'
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check for Linting Errors
    defaults:
      run:
        working-directory: packages/litellm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for Linting Issues
        run: flake8 custom/ tests/

  unit-testing:
    runs-on: ubuntu-latest
    name: Check for Linting Errors
    defaults:
      run:
        working-directory: packages/litellm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for Linting Issues
        run: flake8 custom/ tests/
