locals {
  psql_ssl_ca_path = "/psql/ca.crt"
  psql_ssl_cert_path = "/psql/tls.crt"
  psql_ssl_key_path = "/psql/tsl.key"
}


# Automatically generated by CrunchyData Operator
data "kubernetes_secret_v1" "db_user" {
  metadata {
    name = "preaa-psql-pguser-n8n"
    namespace = var.namespace
  }
}

# Automatically generated by CrunchyData Operator
data "kubernetes_secret_v1" "db_keys" {
  metadata {
    name = "preaa-psql-cluster-cert"
    namespace = var.namespace
  }
}

resource "kubernetes_secret_v1" "database" {
  metadata {
    name = "preaa-n8n-db-creds"
    namespace = var.namespace
  }
  data = {
    # Known values
    "DB_TYPE" = "postgresdb"
    "DB_POSTGRESDB_DATABASE" = "n8n"

    # Pulled from CrunchyData generated secret
    "DB_POSTGRESDB_HOST" = data.kubernetes_secret_v1.db_user.data["host"]
    "DB_POSTGRESDB_PORT" = data.kubernetes_secret_v1.db_user.data["port"]
    "DB_POSTGRESDB_USER" = data.kubernetes_secret_v1.db_user.data["user"]
    "DB_POSTGRESDB_PASSWORD" = data.kubernetes_secret_v1.db_user.data["password"]

    # TLS config, reference mounting points
    "DB_POSTGRESDB_SSL_CA" = local.psql_ssl_ca_path
    "DB_POSTGRESDB_SSL_CERT" = local.psql_ssl_cert_path
    "DB_POSTGRESDB_SSL_KEY" = local.psql_ssl_key_path
  }
}
