locals {
  psql_ssl_ca_path = "/psql/ca.crt"
  psql_ssl_cert_path = "/psql/tls.crt"
  psql_ssl_key_path = "/psql/tls.key"
  psql_ssl_mount = "n8n-psql-ssl"
  app_name = "preaa-n8n"
  storage_name = "preaa-n8n-storage"
  cache_storage_name = "preaa-n8n-cache-storage"
  n8n_port = 5678
}

# Automatically generated by CrunchyData Operator
data "kubernetes_secret_v1" "db_keys" {
  metadata {
    name = "preaa-psql-cluster-cert"
    namespace = var.namespace
  }
}

resource "kubernetes_persistent_volume_claim_v1" "storage" {
  metadata {
    name = local.storage_name
    namespace = var.namespace
  }
  spec {
    access_modes = ["ReadWriteOnce"]
    resources {
      requests = {
        storage = "25Gi"
      }
    }
  }
}

resource "kubernetes_persistent_volume_claim_v1" "cache" {
  metadata {
    name = local.cache_storage_name
    namespace = var.namespace
  }
  spec {
    access_modes = ["ReadWriteOnce"]
    resources {
      requests = {
        storage = "5Gi"
      }
    }
  }
}

resource "kubernetes_secret_v1" "database" {
  metadata {
    name = "preaa-n8n-db-creds"
    namespace = var.namespace
  }
  data = {
    # Known values
    "DB_TYPE" = "postgresdb"
    "DB_POSTGRESDB_DATABASE" = "n8n"

    # Pulled from CrunchyData generated secret
    "DB_POSTGRESDB_HOST" = var.db_creds.host
    "DB_POSTGRESDB_PORT" = var.db_creds.port
    "DB_POSTGRESDB_USER" = var.db_creds.user
    "DB_POSTGRESDB_PASSWORD" = var.db_creds.password
    "DB_POSTGRESDB_SCHEMA" = var.db_creds.user

    # TLS config, paths will be mounted into the container
    "DB_POSTGRESDB_SSL_CA_FILE" = local.psql_ssl_ca_path
    "DB_POSTGRESDB_SSL_CERT_FILE" = local.psql_ssl_cert_path
    "DB_POSTGRESDB_SSL_KEY_FILE" = local.psql_ssl_key_path
  }
}

resource "kubernetes_config_map_v1" "settings" {
  metadata {
    name = "preaa-n8n-settings"
    namespace = var.namespace
  }
  data = {
    "N8N_HOST" = var.hostname
    "WEBHOOK_URL" = var.webhook_url
    "N8N_PROTOCOL" = "https"
    "N8N_DIAGNOSTICS_ENABLED" = false
    "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS" = true
    "N8N_RUNNERS_ENABLED" = true
    "N8N_PORT" = local.n8n_port
  }
}

resource "kubernetes_deployment_v1" "n8n" {
  metadata {
    name = local.app_name
    namespace = var.namespace
    labels = {
      app = local.app_name
    }
  }
  spec {
    replicas = 1
    selector {
      match_labels = {
        app = local.app_name
      }
    }
    template {
      metadata {
        labels = {
          app = local.app_name
        }
      }
      spec {
        container {
          name = local.app_name
          image = "docker.n8n.io/n8nio/n8n:${var.n8n_version}"

          # Resources based on NERC SKUs
          resources {
            limits = {
              memory = "4Gi"
              cpu = "1"
            }
            requests = {
              memory = "4Gi"
              cpu = "1"
            }
          }

          # Database SSL files
          volume_mount {
            name = local.psql_ssl_mount
            mount_path = "/psql"
          }

          # Local storage
          volume_mount {
            name = local.storage_name
            mount_path = "/.n8n"
          }

          # Cache
          volume_mount {
            name = local.cache_storage_name
            mount_path = "/.cache"
          }

          # Database connection settings
          env_from {
            secret_ref {
              name = kubernetes_secret_v1.database.metadata.0.name
            }
          }

          # n8n settings
          env_from {
            config_map_ref {
              name = kubernetes_config_map_v1.settings.metadata.0.name
            }
          }

          port {
            container_port = local.n8n_port
          }
        }

        image_pull_secrets {
          name = var.docker_pull_secret
        }

        restart_policy = "Always"

        volume {
          name = local.psql_ssl_mount
          secret {
            secret_name = data.kubernetes_secret_v1.db_keys.metadata.0.name
          }
        }

        volume {
          name = local.storage_name
          persistent_volume_claim {
            claim_name = kubernetes_persistent_volume_claim_v1.storage.metadata.0.name
          }
        }
        volume {
          name = local.cache_storage_name
          persistent_volume_claim {
            claim_name = kubernetes_persistent_volume_claim_v1.cache.metadata.0.name
          }
        }
      }
    }
  }
}

resource "kubernetes_service_v1" "n8n" {
  metadata {
    name = "preaa-n8n-service"
    namespace = var.namespace
  }
  spec {
    selector = {
      app = local.app_name
    }
    type = "ClusterIP"
    port {
      port = local.n8n_port
    }
  }
}

resource "kubernetes_manifest" "route" {
  manifest = {
    kind       = "Route"
    apiVersion = "route.openshift.io/v1"
    metadata = {
      name      = "preaa-n8n-route"
      namespace = var.namespace
      labels = {
        app = local.app_name
      }
    }
    spec = {
      host = var.hostname
      to = {
        kind = "Service"
        name = kubernetes_service_v1.n8n.metadata.0.name
      }
      port = {
        targetPort = kubernetes_service_v1.n8n.spec.0.port.0.port
      }
      tls = {
        termination                   = "edge"
        insecureEdgeTerminationPolicy = "Redirect"
      }
    }
  }
}
